export interface ProductSpec {
  label: string;
  value: string;
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  model: string;
  category: string;
  categorySlug: string;
  image: string;
  shortDesc: string;
  description: string;
  tag: string;
  features: string[];
  specs: ProductSpec[];
  applications: string[];
  inStock: boolean;
}

export const ALL_PRODUCTS: Product[] = [
  // ================= 1. HIGH PRESSURE WASHERS =================
  {
    id: "hpw-150",
    slug: "high-pressure-washer-150",
    name: "TUQO PRO 150 Bar Induction Pressure Washer",
    model: "TUQO-HPW-150PRO",
    category: "High Pressure Washer",
    categorySlug: "high-pressure-washer",
    image: "/images/cat-pressure-washer.png",
    shortDesc: "Commercial grade 150 Bar induction washer with brass pump head for car washes and industrial cleaning.",
    description: "The TUQO-HPW-150PRO delivers rugged, continuous cleaning power with a heavy 100% pure copper induction motor and precision-machined brass crankshaft pump. Engineered for commercial car detailing, factory degreasing, and heavy machinery wash bays.",
    tag: "Best Seller",
    features: [
      "100% Pure Copper Induction Motor (Low Noise & Long Life)",
      "Heavy Forged Brass Crankshaft Pump with Ceramic Pistons",
      "Auto Total Stop System (TSS) for Motor Longevity",
      "Steel-Braided 10m High Pressure Anti-Kink Hose",
      "Thermal Overload Circuit Protection Switch",
      "Integrated Detergent / Foam Suction Valve",
    ],
    specs: [
      { label: "Max Operating Pressure", value: "150 BAR (2175 PSI)" },
      { label: "Rated Flow Rate", value: "11.5 Liters / Min" },
      { label: "Motor Power", value: "2200W (2.95 HP)" },
      { label: "Motor Type", value: "100% Pure Copper Induction" },
      { label: "Pump Construction", value: "Forged Brass Triplex Plunger" },
      { label: "Voltage / Frequency", value: "220V - 240V / 50Hz Single Phase" },
      { label: "Hose Length", value: "10 Meters Steel Braided" },
      { label: "Weight", value: "22.5 KG" },
      { label: "Warranty", value: "1 Year Commercial Motor Warranty" },
    ],
    applications: [
      "Automotive Detailing Studios & Car Wash Bays",
      "Industrial Plant Floor & Equipment Degreasing",
      "Heavy Construction Fleet Cleaning",
      "Commercial Building Facades & Pavements",
    ],
    inStock: true,
  },
  {
    id: "hpw-180",
    slug: "high-pressure-washer-180",
    name: "TUQO PRO 180 Bar Commercial Pressure Washer",
    model: "TUQO-HPW-180COMM",
    category: "High Pressure Washer",
    categorySlug: "high-pressure-washer",
    image: "/images/cat-pressure-washer.png",
    shortDesc: "High-volume 180 Bar washer with dual pressure regulation and mobile heavy-duty wheeled chassis.",
    description: "Designed for intensive industrial duty, the TUQO-HPW-180COMM features a massive 2800W copper induction unit, adjustable unloader valve, and large puncture-proof wheels for effortless jobsite mobility.",
    tag: "Commercial Pro",
    features: [
      "2800W Heavy-Duty 4-Pole Low RPM Induction Motor",
      "Triplex Brass Pump with Solid Ceramic Plungers",
      "Glycerine-Filled Stainless Steel Pressure Gauge",
      "Heavy Tubular Steel Transport Roll Cage Chassis",
      "Quick Connect Brass Coupler Nozzle System",
    ],
    specs: [
      { label: "Max Operating Pressure", value: "180 BAR (2610 PSI)" },
      { label: "Rated Flow Rate", value: "13.0 Liters / Min" },
      { label: "Motor Power", value: "2800W (3.75 HP)" },
      { label: "Pump Type", value: "Triplex Brass Crankcase" },
      { label: "Voltage", value: "230V / 50Hz Single Phase" },
      { label: "Hose Length", value: "12 Meters Steel Reinforced" },
      { label: "Weight", value: "28.0 KG" },
      { label: "Warranty", value: "1 Year TUQO Industrial Warranty" },
    ],
    applications: [
      "High-Traffic Commercial Vehicle Wash Bays",
      "Poultry & Food Processing Plant Sanitation",
      "Marine Hull & Boat Cleaning",
      "Heavy Machinery & Earthmoving Equipment",
    ],
    inStock: true,
  },
  {
    id: "hpw-220",
    slug: "high-pressure-washer-220",
    name: "TUQO PRO 220 Bar Heavy Triplex Washer",
    model: "TUQO-HPW-220TRIPLEX",
    category: "High Pressure Washer",
    categorySlug: "high-pressure-washer",
    image: "/images/cat-pressure-washer.png",
    shortDesc: "Extreme duty 220 Bar 3-Phase pressure washer for continuous round-the-clock plant cleaning operations.",
    description: "The peak of industrial washing performance. Built with a continuous-duty 3-phase motor, oversized brass manifold, and direct drive triplex pump that effortlessly strips paint, scale, grease, and tough grime.",
    tag: "Extreme Industrial",
    features: [
      "4000W 3-Phase Continuous Duty Induction Motor",
      "Industrial Brass Manifold with Stainless Steel Valves",
      "Low RPM Operation for Cool Running & 24/7 Duty",
      "Built-in Thermal Dump Valve for Pump Protection",
      "15m Heavy Steel-Braided Hydraulic Hose",
    ],
    specs: [
      { label: "Max Operating Pressure", value: "220 BAR (3190 PSI)" },
      { label: "Rated Flow Rate", value: "15.0 Liters / Min" },
      { label: "Motor Power", value: "4000W (5.4 HP)" },
      { label: "Motor Phase", value: "415V / 50Hz 3-Phase" },
      { label: "Pump Head", value: "Precision Forged Solid Brass" },
      { label: "Hose Length", value: "15 Meters Wire-Braided" },
      { label: "Weight", value: "38.5 KG" },
      { label: "Warranty", value: "1 Year Commercial Warranty" },
    ],
    applications: [
      "Heavy Manufacturing & Steel Mills",
      "Concrete & Masonry Formwork Restoration",
      "Commercial Truck & Bus Fleets",
      "Agricultural Machinery & Silo Washing",
    ],
    inStock: true,
  },
  {
    id: "hpw-compact-120",
    slug: "high-pressure-washer-compact-120",
    name: "TUQO Compact Pro 120 Bar Portable Washer",
    model: "TUQO-HPW-120CPT",
    category: "High Pressure Washer",
    categorySlug: "high-pressure-washer",
    image: "/images/cat-pressure-washer.png",
    shortDesc: "Lightweight, portable 120 Bar washer ideal for mobile detailing, AC servicing, and workshop maintenance.",
    description: "Engineered for contractors who need powerful pressure in a compact footprint. Features self-priming suction, making it capable of drawing water directly from buckets or storage tanks without tap pressure.",
    tag: "Portable Pro",
    features: [
      "Self-Priming Suction Function (Bucket Draw Capability)",
      "High Efficiency Compact Copper Motor",
      "Ergonomic Carry Handle & On-Board Gun Storage",
      "Adjustable Multi-Pattern Spray Lance Included",
    ],
    specs: [
      { label: "Max Operating Pressure", value: "120 BAR (1740 PSI)" },
      { label: "Rated Flow Rate", value: "8.5 Liters / Min" },
      { label: "Motor Power", value: "1600W (2.1 HP)" },
      { label: "Voltage", value: "220V - 240V / 50Hz" },
      { label: "Hose Length", value: "8 Meters High-Flex" },
      { label: "Weight", value: "9.2 KG" },
      { label: "Warranty", value: "1 Year Warranty" },
    ],
    applications: [
      "Mobile Car Detailing Services",
      "HVAC & AC Condenser Coil Cleaning",
      "Residential & Commercial Property Maintenance",
      "Motorcycle & Bicycle Service Shops",
    ],
    inStock: true,
  },
  {
    id: "hpw-diesel-250",
    slug: "high-pressure-washer-diesel-250",
    name: "TUQO Industrial Engine Driven 250 Bar Washer",
    model: "TUQO-HPW-250DIESEL",
    category: "High Pressure Washer",
    categorySlug: "high-pressure-washer",
    image: "/images/cat-pressure-washer.png",
    shortDesc: "Independent diesel-engine driven 250 Bar washer for remote jobsites with no electrical grid connection.",
    description: "Maximum cleaning force wherever you go. Powered by a high-torque 4-stroke industrial diesel engine coupled to a direct-drive ceramic piston brass pump with automatic low-oil shutdown.",
    tag: "Heavy Field Unit",
    features: [
      "Heavy 4-Stroke Commercial Engine with Electric Start",
      "Heavy All-Terrain Pneumatic Wheels on Steel Chassis",
      "Industrial Brass Pump with Easy Pressure Adjustment",
      "Complete 5-Piece Quick Connect Spray Nozzle Set",
    ],
    specs: [
      { label: "Max Operating Pressure", value: "250 BAR (3625 PSI)" },
      { label: "Rated Flow Rate", value: "16.0 Liters / Min" },
      { label: "Engine Power", value: "7.5 HP Commercial Engine" },
      { label: "Starting System", value: "Recoil / Electric Key Start" },
      { label: "Hose Length", value: "15 Meters Steel Braided" },
      { label: "Weight", value: "48.0 KG" },
      { label: "Warranty", value: "1 Year Engine & Pump Warranty" },
    ],
    applications: [
      "Remote Construction & Road Building Sites",
      "Mining & Quarry Equipment Cleaning",
      "Agricultural Field Implements",
      "Off-Grid Industrial Shipyards",
    ],
    inStock: true,
  },

  // ================= 2. VACUUM CLEANERS =================
  {
    id: "vc-150",
    slug: "vacuum-cleaner-150",
    name: "TUQO PRO 30L Wet & Dry Stainless Steel Vacuum",
    model: "TUQO-VC-30SS",
    category: "Vacuum Cleaner",
    categorySlug: "vacuum-cleaner",
    image: "/images/cat-vacuum-cleaner.png",
    shortDesc: "High-suction 30L wet & dry vacuum with corrosion-resistant SS304 barrel and multi-stage filtration.",
    description: "Built for heavy workshop dust, wood chips, metal filings, and liquid spill extraction. Equipped with a high-torque copper turbine motor, washable cartridge filter, and heavy-duty 360° castor base.",
    tag: "Workshop Favorite",
    features: [
      "Heavy 304 Stainless Steel Rust-Proof Drum",
      "Powerful 1400W High Airflow By-Pass Copper Motor",
      "Washable HEPA Cartridge Filter + Wet Foam Barrier",
      "Blower Port Function for Clearing Leaves & Debris",
      "360° Swivel Locking Caster Wheels",
    ],
    specs: [
      { label: "Drum Capacity", value: "30 Liters (Stainless Steel)" },
      { label: "Motor Power", value: "1400 Watts By-Pass" },
      { label: "Vacuum Suction", value: "22 kPa (220 mbar)" },
      { label: "Air Flow Rate", value: "58 Liters / Sec" },
      { label: "Voltage", value: "220V - 240V / 50Hz" },
      { label: "Hose Length", value: "2.5 Meters Heavy-Flex" },
      { label: "Power Cord", value: "5 Meters Industrial Rubber" },
      { label: "Weight", value: "8.5 KG" },
      { label: "Warranty", value: "1 Year Motor Warranty" },
    ],
    applications: [
      "Automotive Interior Detailing & Carpet Extraction",
      "Woodworking & Carpentry Sawdust Collection",
      "Commercial Warehouses & Retail Stores",
      "Liquid Spill Cleanup & Floor Drying",
    ],
    inStock: true,
  },
  {
    id: "vc-60l",
    slug: "vacuum-cleaner-industrial-60l",
    name: "TUQO Dual Motor 60L Heavy Vacuum System",
    model: "TUQO-VC-60DUAL",
    category: "Vacuum Cleaner",
    categorySlug: "vacuum-cleaner",
    image: "/images/cat-vacuum-cleaner.png",
    shortDesc: "Dual motor 60L extraction vacuum with independent motor switching for continuous industrial service.",
    description: "Features dual independently controlled 1200W vacuum motors delivering exceptional 2400W total suction power for demanding factories, large wash bays, and commercial maintenance teams.",
    tag: "Dual Motor Power",
    features: [
      "Dual 1200W (2400W Total) Independent Motors",
      "Heavy 60 Liter Stainless Steel Container with Bottom Drain Hose",
      "Anti-Static Grounding Chain & Industrial Caster Carriage",
      "Large Diameter 40mm Suction Hose for Bulky Debris",
    ],
    specs: [
      { label: "Drum Capacity", value: "60 Liters" },
      { label: "Motor Power", value: "2400W (2 x 1200W Dual Motor)" },
      { label: "Vacuum Suction", value: "28 kPa" },
      { label: "Air Flow Rate", value: "106 Liters / Sec" },
      { label: "Drainage", value: "External Bottom Waste Drain Hose" },
      { label: "Hose Diameter", value: "40 mm Industrial" },
      { label: "Weight", value: "19.5 KG" },
      { label: "Warranty", value: "1 Year Industrial Warranty" },
    ],
    applications: [
      "High Volume Car Detailing Bays",
      "Metal Machining & CNC Workshop Debris",
      "Construction Post-Renovation Cleanup",
      "Textile & Garment Manufacturing Mills",
    ],
    inStock: true,
  },
  {
    id: "vc-80l",
    slug: "vacuum-cleaner-commercial-80l",
    name: "TUQO Triple Turbine 80L Heavy Industrial Vacuum",
    model: "TUQO-VC-80TRIPLE",
    category: "Vacuum Cleaner",
    categorySlug: "vacuum-cleaner",
    image: "/images/cat-vacuum-cleaner.png",
    shortDesc: "Triple motor 3600W 80L continuous vacuum system engineered for heavy debris and slurry collection.",
    description: "The ultimate industrial suction machine. Three heavy-duty motors operate together or independently on a rugged tipping trolley chassis designed for quick emptying into bulk disposal bins.",
    tag: "Heavy Duty 3600W",
    features: [
      "Triple 1200W Motors (3600W Total Peak Suction)",
      "Easy-Tilt Pivot Carriage for Quick Drum Dumping",
      "Reinforced Multi-Stage Cloth & Sponge Washable Filters",
      "Wide Front Squeegee Tool Compatibility",
    ],
    specs: [
      { label: "Drum Capacity", value: "80 Liters" },
      { label: "Motor Power", value: "3600W (3 x 1200W Motors)" },
      { label: "Vacuum Suction", value: "32 kPa (320 mbar)" },
      { label: "Air Flow Rate", value: "159 Liters / Sec" },
      { label: "Chassis", value: "Heavy Tubular Steel Pivot Dumping Frame" },
      { label: "Weight", value: "27.0 KG" },
      { label: "Warranty", value: "1 Year Warranty" },
    ],
    applications: [
      "Large Scale Manufacturing Facilities",
      "Commercial Airport & Railway Maintenance",
      "Flood Water Remediation & Industrial Slurry",
      "Heavy Concrete Grinding Dust Extraction",
    ],
    inStock: true,
  },
  {
    id: "vc-carpet-ext",
    slug: "vacuum-cleaner-carpet-extractor",
    name: "TUQO Pro Spray & Extraction Cleaner 40L",
    model: "TUQO-VC-40EXTRACT",
    category: "Vacuum Cleaner",
    categorySlug: "vacuum-cleaner",
    image: "/images/cat-vacuum-cleaner.png",
    shortDesc: "High-pressure detergent injection and deep extraction vacuum for vehicle upholstery and carpets.",
    description: "Combines a precision chemical injection pump with a high-lift vacuum motor to spray detergent deep into fabric fibers and instantly extract soiled water, leaving interiors clean and nearly dry.",
    tag: "Auto Detailing Special",
    features: [
      "Built-in High Pressure Detergent Solution Pump",
      "Transparent Hand Tool for Real-Time Suction Monitoring",
      "Dual Separate Clean Water & Waste Solution Tanks",
      "Stainless Steel Floor Wand + Hand Upholstery Wand",
    ],
    specs: [
      { label: "Waste Tank Capacity", value: "40 Liters Stainless Steel" },
      { label: "Clean Solution Tank", value: "10 Liters Chemical Resistant" },
      { label: "Vacuum Motor", value: "1400W High Lift" },
      { label: "Solution Pump", value: "35W Diaphragm (4 BAR)" },
      { label: "Weight", value: "16.0 KG" },
      { label: "Warranty", value: "1 Year TUQO Warranty" },
    ],
    applications: [
      "Car Seat, Headliner & Floor Carpet Detailing",
      "Hotel & Office Upholstery Maintenance",
      "Sofa, Mattress & Furniture Deep Cleaning",
    ],
    inStock: true,
  },

  // ================= 3. AIR COMPRESSORS =================
  {
    id: "ac-150",
    slug: "air-compressor-150",
    name: "TUQO PRO 50L Direct Drive Air Compressor",
    model: "TUQO-AC-50DIRECT",
    category: "Air Compressor",
    categorySlug: "air-compressor",
    image: "/images/cat-air-compressor.png",
    shortDesc: "High performance 50L direct-drive compressor for spray painting, impact wrenches, and tire inflation.",
    description: "The TUQO-AC-50DIRECT is engineered for rapid pressure recovery and long duty cycles. Features an aluminum alloy crankcase with cast iron cylinder sleeve for optimum heat dissipation and maximum piston life.",
    tag: "Workshop Standard",
    features: [
      "100% Copper Wound 2.5 HP Electric Motor",
      "Heavy Cast Iron Cylinder with Precision Ring Set",
      "Dual Air Outlets with Quick Release Nitto Couplers",
      "Automatic Pressure Switch with Safety Relief Valve",
      "Vibration-Damping Rubber Mounts & Transport Wheels",
    ],
    specs: [
      { label: "Tank Capacity", value: "50 Liters (Powder Coated Steel)" },
      { label: "Motor Power", value: "2.5 HP (1850 Watts)" },
      { label: "Max Working Pressure", value: "8 BAR (116 PSI)" },
      { label: "Air Delivery (FAD)", value: "210 Liters / Min" },
      { label: "Speed", value: "2850 RPM" },
      { label: "Voltage", value: "220V - 240V / 50Hz" },
      { label: "Weight", value: "32.0 KG" },
      { label: "Warranty", value: "1 Year Motor & Tank Warranty" },
    ],
    applications: [
      "Spray Painting & Automotive Body Refinishing",
      "Pneumatic Impact Wrenches & Ratchets",
      "Tire Inflation & Pressure Testing",
      "Air Nailing, Stapling & Workshop Blow Guns",
    ],
    inStock: true,
  },
  {
    id: "ac-belt-100l",
    slug: "air-compressor-belt-100l",
    name: "TUQO PRO 100L Belt Driven Twin Cylinder Compressor",
    model: "TUQO-AC-100BELT",
    category: "Air Compressor",
    categorySlug: "air-compressor",
    image: "/images/cat-air-compressor.png",
    shortDesc: "Low RPM heavy belt-driven twin cylinder 100L compressor built for non-stop industrial pneumatic tools.",
    description: "Belt-driven configuration ensures low pump speeds, lower operating temperatures, and ultra-quiet running under demanding multi-operator workshop demands.",
    tag: "Heavy Workshop",
    features: [
      "Heavy Cast Iron V-Twin Cylinder Pump Block",
      "Low RPM Belt Drive for Extreme Longevity",
      "Dual Industrial Pressure Gauges & Regulator Filter Unit",
      "Heavy 100L Certified Pressure Vessel",
    ],
    specs: [
      { label: "Tank Capacity", value: "100 Liters" },
      { label: "Motor Power", value: "3.0 HP (2250 Watts)" },
      { label: "Max Working Pressure", value: "10 BAR (145 PSI)" },
      { label: "Air Delivery (FAD)", value: "320 Liters / Min" },
      { label: "Pump Speed", value: "1150 RPM (Low Wear)" },
      { label: "Weight", value: "68.0 KG" },
      { label: "Warranty", value: "1 Year Commercial Warranty" },
    ],
    applications: [
      "Commercial Tyre Service Centers & Garages",
      "Automotive Paint Booth Continuous Spraying",
      "Sandblasting & Pneumatic Sanding Lines",
      "Heavy Fabrication Workshops",
    ],
    inStock: true,
  },
  {
    id: "ac-silent-30l",
    slug: "air-compressor-silent-oil-free-30l",
    name: "TUQO Ultra Silent Oil-Free Compressor 30L",
    model: "TUQO-AC-30SILENT",
    category: "Air Compressor",
    categorySlug: "air-compressor",
    image: "/images/cat-air-compressor.png",
    shortDesc: "Super quiet 60dB oil-free air compressor delivering 100% clean air for dental clinics and indoor studios.",
    description: "Engineered with dual silent oil-free pump heads, generating zero exhaust oil vapor and operating at conversation volume (under 60 dB). No oil maintenance required.",
    tag: "Ultra Quiet & Clean",
    features: [
      "Ultra-Quiet Operation (< 60 dB Noise Level)",
      "100% Oil-Free Clean Air Output (No Maintenance)",
      "Dual Copper Cylinder Heads with Teflon Coated Pistons",
      "Built-in Solenoid Valve for Quick Motor Start Relief",
    ],
    specs: [
      { label: "Tank Capacity", value: "30 Liters" },
      { label: "Motor Power", value: "1.5 HP (1100W)" },
      { label: "Max Pressure", value: "8 BAR (116 PSI)" },
      { label: "Noise Level", value: "< 60 dB(A)" },
      { label: "Air Output", value: "135 Liters / Min" },
      { label: "Weight", value: "21.0 KG" },
      { label: "Warranty", value: "1 Year Warranty" },
    ],
    applications: [
      "Dental Clinics & Medical Equipment",
      "Indoor Spray Tanning & Airbrush Art Studios",
      "Electronics Assembly & Pneumatic Automation",
      "Laboratories & Clean Room Environments",
    ],
    inStock: true,
  },

  // ================= 4. FOAM DISPENSERS =================
  {
    id: "fd-150",
    slug: "foam-dispenser-150",
    name: "TUQO PRO 1L Brass Quick-Connect Snow Foam Cannon",
    model: "TUQO-FD-1LCANNON",
    category: "Foam Dispenser",
    categorySlug: "foam-dispenser",
    image: "/images/cat-foam-dispenser.png",
    shortDesc: "High-density snow foam lance with solid brass core and adjustable spray angle for touchless washing.",
    description: "Crafted with solid brass valve components, a stainless steel mesh aerator, and a wide-mouth HDPE bottle for mixing thick shaving-cream foam that clings to paintwork and loosens grit.",
    tag: "Detailing Essential",
    features: [
      "Solid Brass Heavy Body with Stainless Steel Aerator",
      "Adjustable Foam Concentration Flow Dial (+ / -)",
      "360° Rotating Vertical to Horizontal Fan Pattern",
      "1/4\" Quick-Connect Stainless Plug Included",
      "Wide-Base 1 Liter Calibrated Bottle (Anti-Tip)",
    ],
    specs: [
      { label: "Bottle Capacity", value: "1.0 Liter (1000 ml)" },
      { label: "Pressure Range", value: "70 BAR to 220 BAR (1000 - 3200 PSI)" },
      { label: "Min Water Flow", value: "5.5 Liters / Min" },
      { label: "Max Water Temp", value: "60°C (140°F)" },
      { label: "Connector", value: "1/4 Inch Quick Release Brass" },
      { label: "Body Material", value: "Forged Brass + HDPE Bottle" },
      { label: "Warranty", value: "6 Months Commercial Warranty" },
    ],
    applications: [
      "Automotive Touchless Pre-Wash Foaming",
      "Commercial Truck & Bus Fleet Washing",
      "Motorcycle & Bicycle Deep Cleaning",
      "Industrial Floor & Machine Degreasing",
    ],
    inStock: true,
  },
  {
    id: "fd-tank-70l",
    slug: "foam-dispenser-stainless-70l",
    name: "TUQO Heavy Stainless Steel 70L Foam Tank",
    model: "TUQO-FD-70SSTANK",
    category: "Foam Dispenser",
    categorySlug: "foam-dispenser",
    image: "/images/cat-foam-dispenser.png",
    shortDesc: "Pneumatic 70L stainless steel pressurized tank for continuous high-volume wash bay foaming.",
    description: "Connects to any standard air compressor. Delivers massive volumes of thick foam through an 8-meter hose without requiring a pressure washer running simultaneously.",
    tag: "Wash Bay Heavy Tank",
    features: [
      "Heavy 304 Stainless Steel Certified Pressure Vessel",
      "Built-in Air Pressure Regulator & Safety Relief Valve",
      "Transparent Level Indicator Tube for Solution Level Check",
      "8m Heavy Chemical Resistant Foam Delivery Hose + Brass Lance",
    ],
    specs: [
      { label: "Tank Capacity", value: "70 Liters" },
      { label: "Working Air Pressure", value: "2 - 4 BAR (30 - 60 PSI)" },
      { label: "Material", value: "Grade 304 Stainless Steel" },
      { label: "Hose Length", value: "8 Meters Spiral Reinforced" },
      { label: "Lance", value: "Stainless Steel Foam Lance with Brass Nozzle" },
      { label: "Weight", value: "17.5 KG" },
      { label: "Warranty", value: "1 Year Warranty" },
    ],
    applications: [
      "High Volume Commercial Car Washes",
      "Fleet Service Depots & Bus Garages",
      "Industrial Food Processing Plant Hygiene",
    ],
    inStock: true,
  },

  // ================= 5. POWER TOOLS =================
  {
    id: "pt-150",
    slug: "power-tool-150",
    name: "TUQO PRO 21V Brushless Cordless Impact Drill Kit",
    model: "TUQO-PT-21VIMPACT",
    category: "Power Tools",
    categorySlug: "power-tools",
    image: "/images/cat-power-tools.png",
    shortDesc: "High-torque 65Nm brushless impact drill with dual 4.0Ah lithium batteries and metal ratcheting chuck.",
    description: "Engineered for demanding masonry, steel drilling, and heavy timber driving. Brushless motor technology provides 50% more runtime, zero brush maintenance, and exceptional durability.",
    tag: "Brushless Pro Kit",
    features: [
      "High-Torque Brushless Motor (65 Nm Peak Torque)",
      "2-Speed All-Metal Gearbox (0-550 / 0-2100 RPM)",
      "20+3 Torque Stage Clutch with Hammer Impact Mode",
      "13mm (1/2\") Heavy Keyless Steel Ratcheting Chuck",
      "Dual 21V 4.0Ah High-Drain Lithium-Ion Battery Packs",
      "Heavy BMC Carry Case with 24-Piece Accessory Bit Kit",
    ],
    specs: [
      { label: "Battery Voltage", value: "21V Max Lithium-Ion" },
      { label: "Battery Capacity", value: "4.0 Ah (Dual Pack Included)" },
      { label: "Max Torque", value: "65 Nm" },
      { label: "No-Load Speed", value: "0-550 / 0-2100 RPM" },
      { label: "Impact Rate", value: "0 - 31,500 BPM" },
      { label: "Chuck Capacity", value: "1.5 - 13 mm Metal Keyless" },
      { label: "Weight (with battery)", value: "1.65 KG" },
      { label: "Warranty", value: "1 Year Tool & Battery Warranty" },
    ],
    applications: [
      "Masonry & Brick Wall Anchor Installation",
      "Structural Steel Fabrication & Fastening",
      "Commercial Carpentry, Cabinetry & Roofing",
      "HVAC & Electrical Conduit Mounting",
    ],
    inStock: true,
  },
  {
    id: "pt-grinder-850w",
    slug: "power-tool-angle-grinder-850w",
    name: "TUQO Heavy 850W 100mm Angle Grinder",
    model: "TUQO-PT-850GRIND",
    category: "Power Tools",
    categorySlug: "power-tools",
    image: "/images/cat-power-tools.png",
    shortDesc: "High power 850W angle grinder with epoxy-coated armature and labyrinth dust seal bearings.",
    description: "Built for heavy metal cutting, weld seam grinding, and stone dressing. Heavy epoxy protection prevents conductive metal dust from damaging motor windings.",
    tag: "Metal Fabrication",
    features: [
      "850W High-Heat Resistant 100% Copper Armature",
      "Labyrinth Air Intakes & Sealed Ball Bearings",
      "Tool-Free Burst Proof Wheel Safety Guard",
      "Slim Body Grip for Comfortable Single-Hand Control",
    ],
    specs: [
      { label: "Wheel Diameter", value: "100 mm (4 Inch)" },
      { label: "Rated Power", value: "850 Watts" },
      { label: "No Load Speed", value: "11,000 RPM" },
      { label: "Spindle Thread", value: "M10" },
      { label: "Voltage", value: "220V - 240V / 50Hz" },
      { label: "Weight", value: "1.85 KG" },
      { label: "Warranty", value: "1 Year TUQO Warranty" },
    ],
    applications: [
      "Metal Bar, Pipe & Sheet Metal Cutting",
      "Weld Seam Smoothing & Rust Removal",
      "Tile & Granite Edge Dressing",
    ],
    inStock: true,
  },
  {
    id: "pt-core-drill",
    slug: "power-tool-core-drill-machine",
    name: "TUQO 2300W Heavy Concrete Core Drill",
    model: "TUQO-PT-2300CORE",
    category: "Power Tools",
    categorySlug: "power-tools",
    image: "/images/cat-power-tools.png",
    shortDesc: "Heavy 2300W diamond core drilling machine with water cooling feed for concrete and granite.",
    description: "Heavy-duty wet and dry core drill with built-in safety mechanical clutch and water swivel for plumbing, AC conduit, and electrical penetration drilling.",
    tag: "Heavy Construction",
    features: [
      "2300W Extreme Torque Motor with Overload Protection",
      "Integrated Water Swivel for Wet Diamond Core Bits",
      "Mechanical Safety Slip Clutch Prevents Kickback",
      "Stepless Speed Regulation (0-1400 RPM)",
    ],
    specs: [
      { label: "Max Drilling Dia", value: "165 mm (Concrete)" },
      { label: "Motor Power", value: "2300 Watts" },
      { label: "Speed", value: "0 - 1400 RPM" },
      { label: "Spindle Thread", value: "1-1/4\" UNC & 1/2\" BSP" },
      { label: "Weight", value: "6.8 KG" },
      { label: "Warranty", value: "1 Year Commercial Warranty" },
    ],
    applications: [
      "Plumbing Pipe Core Penetration",
      "HVAC Duct & Split AC Core Holes",
      "Electrical Cable Trays & Conduit Holes",
    ],
    inStock: true,
  },

  // ================= 6. POWER TOOLS ACCESSORIES =================
  {
    id: "acc-tct-cutter",
    slug: "tct-core-cutter-hole-saw",
    name: "TUQO Premium TCT Hole Saw Core Cutter",
    model: "TUQO-ACC-TCTSAW",
    category: "Power Tools Accessories",
    categorySlug: "power-tools-accessories",
    image: "/images/cat-accessories.png",
    shortDesc: "Tungsten carbide tipped (TCT) hole saw with stepped center pilot drill for stainless steel and alloys.",
    description: "Specially formulated carbide teeth ensure fast, burr-free circular cutting through stainless steel sheets, cast iron, structural steel, aluminum, and fiberglass.",
    tag: "Precision Cutting",
    features: [
      "Micro-Grain Tungsten Carbide Cutting Teeth",
      "Stepped Pilot Drill Prevents Tooth Impact Shock",
      "Ejector Spring for Automatic Slug Removal",
      "Reinforced Hex Shank Eliminates Chuck Slippage",
    ],
    specs: [
      { label: "Available Diameters", value: "16mm to 100mm" },
      { label: "Max Cutting Depth", value: "25 mm (1 Inch)" },
      { label: "Tooth Material", value: "Tungsten Carbide Tipped (TCT)" },
      { label: "Shank Type", value: "10mm (3/8\") Three-Flats Hex Shank" },
      { label: "Suitable Materials", value: "Stainless Steel, Mild Steel, Aluminum, FRP" },
    ],
    applications: [
      "Electrical Panel & Junction Box Knockouts",
      "Pipe Entry Holes in Sheet Metal Enclosures",
      "Automotive Body & Chassis Modification",
    ],
    inStock: true,
  },
  {
    id: "acc-diamond-blade",
    slug: "diamond-turbo-cutting-blade",
    name: "TUQO Pro Segmented Diamond Cutting Blade 110mm",
    model: "TUQO-ACC-DIAMOND110",
    category: "Power Tools Accessories",
    categorySlug: "power-tools-accessories",
    image: "/images/cat-accessories.png",
    shortDesc: "Hot-pressed diamond blade for chip-free cutting of granite, marble, tiles, and reinforced concrete.",
    description: "High diamond concentration matrix delivers fast cutting speeds and long blade life on both wet and dry angle grinders and marble cutters.",
    tag: "High Diamond Matrix",
    features: [
      "Hot-Pressed Sintered Diamond Segments",
      "Turbo Rim Design for Rapid Dust Evacuation & Cooling",
      "Universal 20mm Bore with 16mm Reducer Bush",
    ],
    specs: [
      { label: "Blade Diameter", value: "110 mm (4.3 Inch)" },
      { label: "Bore Size", value: "20 mm (with 16mm Brass Bush)" },
      { label: "Max Safe Speed", value: "13,800 RPM (80 m/s)" },
      { label: "Segment Height", value: "10 mm Diamond Depth" },
      { label: "Application", value: "Granite, Marble, Concrete, Ceramic Tiles" },
    ],
    applications: [
      "Granite Countertop & Slab Cutting",
      "Ceramic & Vitrified Floor Tile Laying",
      "Concrete Joint Cutting & Scoring",
    ],
    inStock: true,
  },
  {
    id: "acc-hose-15m",
    slug: "high-pressure-reinforced-hose-15m",
    name: "TUQO 15M Steel-Braided High Pressure Hose",
    model: "TUQO-ACC-HOSE15M",
    category: "Power Tools Accessories",
    categorySlug: "power-tools-accessories",
    image: "/images/cat-accessories.png",
    shortDesc: "Heavy wire-braided 350 Bar replacement high-pressure hose with M22 / Quick-Connect fittings.",
    description: "Steel-wire reinforced rubber hose that resists kinks, abrasions, and extreme pressures up to 350 Bar (5000 PSI). Compatible with all TUQO and major commercial pressure washers.",
    tag: "350 Bar Wire Braided",
    features: [
      "High Tensile Steel Wire Braid Reinforcement",
      "Abrasion & Oil Resistant Outer Rubber Cover",
      "Solid Brass Heavy Swivel End Fittings (Anti-Twist)",
    ],
    specs: [
      { label: "Length", value: "15 Meters (49.2 Feet)" },
      { label: "Max Working Pressure", value: "350 BAR (5075 PSI)" },
      { label: "Burst Pressure", value: "1000 BAR (14,500 PSI)" },
      { label: "Max Water Temp", value: "100°C (Hot Water Ready)" },
      { label: "Fittings", value: "M22 x 1.5mm Female / 3/8\" Quick Release" },
    ],
    applications: [
      "Commercial Car Wash Bay Extension",
      "Factory & Facility Floor Washing",
      "High Reach Wall & Facade Cleaning",
    ],
    inStock: true,
  },
];

export function getProductsByCategory(categorySlug: string): Product[] {
  return ALL_PRODUCTS.filter((p) => p.categorySlug === categorySlug);
}

export function getProductBySlug(slug: string): Product | undefined {
  return ALL_PRODUCTS.find((p) => p.slug === slug);
}
